spring:
  application:
    name: strong_junior_test_task.util

  sql:
    init:
      mode: embedded

  datasource:
    url: jdbc:postgresql://localhost:5432/products_order
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /ui
